Algoritmo "L01G"
// Objetivo: Somar e multiplicar 4 valores em todas as combinações (distributiva).
Var
   A, B, C, D: Inteiro
Inicio
   Escreva("Digite 4 números inteiros: ")
   Leia(A, B, C, D)
   
   // Operações de Adição
   Escreval("Somas: ", A+B, " | ", A+C, " | ", A+D, " | ", B+C, " | ", B+D, " | ", C+D)
   // Operações de Multiplicação
   Escreval("Multiplicações: ", A*B, " | ", A*C, " | ", A*D, " | ", B*C, " | ", B*D, " | ", C*D)
Fimalgoritmo